version: '3.5'

services:
  scalargis:
    build:
      context: .
    image: registry.wkt.pt:5000/wkt/scalargis-client:latest
    container_name: wkt-scalargis-client
    hostname: wkt-scalargis-client
    restart: always
    dns: 8.8.8.8
    ports:
      - "8081:80"
