name: Build and push to WKT registry ScalarGIS core image (by tag)

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build the Docker image
      id: build_image
      run: docker build . --tag registry.wkt.pt/wkt/scalargis:${{ steps.get_version.outputs.VERSION }}

    - name: Login to WKT registry
      id: login_registry
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSW }} registry.wkt.pt

    - name: Push to WKT registry
      id: push_image
      run: docker push registry.wkt.pt/v2/wkt/scalargis:${{ steps.get_version.outputs.VERSION }}
