name: Build and push to WKT registry ScalarGIS Client core image (latest)

on:
  push:
    branch: [ github-actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      id: build_image
      run: docker build . --tag registry.wkt.pt:5000/wkt/scalargis-client:latest
    
    - id: login-docker-registry
      name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSW }}    

    - name: Push to WKT registry
      id: push_image
      run: docker push registry.wkt.pt:5000/wkt/scalargis-client:latest
